### ISSUE TITLE
Manifest download fail

### ISSUE THREAD

**Issue by JrVolt** [ATOMNFT/CM-Box#3]
Hi 
I'm failing to flash the board with the web flasher, i'm trying with Micro'only variant WITH GPS, it says "Fail to download manifest" 
I'm sure it's all waking, i can flash it with frank's web version.

Thanks

**Comment by ATOMNFT** [comment]
Sorry for the delay, but I will take a look at it. Prob a filename mismatch. Thank you. Are you trying the newest version (1.0.0)? this will help me resolve the issue/s.

**Comment by ATOMNFT** [comment]
> Hi I'm failing to flash the board with the web flasher, i'm trying with Micro'only variant WITH GPS, it says "Fail to download manifest" I'm sure it's all waking, i can flash it with frank's web version.
> 
> Thanks

Problem should be resolved now, thanks again.

**Comment by JrVolt** [comment]
Thanks, i'll try again asap, thank you. 

UPDATE, Works fine 
Marauder v1.0.0 WITH GPS
HW : CYD micro only (with mods)
FLASH OK 

GPS untested due to other issues (https://github.com/justcallmekoko/ESP32Marauder/issues/338#issuecomment-2394880648), not sure about evil portal config or file
